---

- hosts: php
  vars: 
    home: "{{ lookup('env','HOME') }}"
  tasks:
  - name: Install Official latest PHP
    become: true
    apt:
      name: 
      - php-cli 
      - php-common
      - php-fpm
      - php-curl
      - php-mysql
      - php-xml
      - php-readline
      - php-tidy
      - php-json
      - php-mbstring
      - php-gd
      - php-opcache
      - php-zip
      - php-pear
      - php-bcmath
      - php-tokenizer
      - unzip
      update_cache: yes
  - name: Create bin folder in user's home
    file:
      path: "{{ home }}/bin"
      state: directory
  - name: Download composer installer
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/installer
    tags: composer
  - name: Install composer
    shell: "cat /tmp/installer | php --install-dir={{ home }}/bin --filename=composer"
    tags: composer
  - name: Set permissions on composer
    file:
      path: "{{ home }}/bin/composer"
      mode: "+x"
    tags: composer
  - name: Install prestissimo (composer parallel install plugin)
    shell: "{{ home }}/bin/composer global require hirak/prestissimo"
    tags: composer
